# Cargo-deny configuration for LSFTP
# Security and license compliance

[advisories]
# Check for security advisories
db-path = "~/.cargo/advisory-db"
db-url = "https://github.com/rustsec/advisory-db"
vulnerability = "deny"
unsound = "deny"
notice = "warn"
ignore = []

[licenses]
# License compliance
default = "deny"
copyleft = "deny"
allow-osi-fsf-free = true
confidence-threshold = 0.8
unlicensed = "deny"
unknown = "deny"
exceptions = [
    # MIT and Apache-2.0 are allowed
    { name = "lsftp-core", license = "MIT OR Apache-2.0" },
    { name = "lsftp-client", license = "MIT OR Apache-2.0" },
    { name = "lsftp-server", license = "MIT OR Apache-2.0" },
    { name = "lsftp-tools", license = "MIT OR Apache-2.0" },
]

[licenses.allow]
# Explicitly allowed licenses
MIT = ["MIT", "MIT-0"]
Apache-2-0 = ["Apache-2.0"]
ISC = ["ISC"]
Unlicense = ["Unlicense"]
Zlib = ["Zlib"]

[licenses.deny]
# Explicitly denied licenses
GPL = ["GPL-1.0", "GPL-2.0", "GPL-3.0"]
LGPL = ["LGPL-2.0", "LGPL-2.1", "LGPL-3.0"]
AGPL = ["AGPL-1.0", "AGPL-3.0"]

[bans]
# Ban specific crates or versions
multiple-versions = "deny"
highlight = "lowest"
skip-tree = []
skip = []

[ban.allowlist]
# Allow specific crates
allow = []

[ban.denylist]
# Deny specific crates
deny = [
    # Known vulnerable crates
    { name = "chrono", version = "=0.4.0" },
    { name = "time", version = "=0.1.0" },
]

[sources]
# Source configuration
unknown-registry = "deny"
unknown-git = "deny"
path-dependencies = "allow"
git = "allow"
registry = "allow"

[sources.allowlist]
# Allowed sources
allow = [
    "https://github.com/rust-lang/crates.io-index",
    "https://github.com/iyotee/LSFTP",
]

[sources.denylist]
# Denied sources
deny = []
